<?php
/**
 * WIKINDX : Bibliographic Management system.
 * @see https://wikindx.sourceforge.io/ The WIKINDX SourceForge project
 * @author The WIKINDX Team
 * @license https://creativecommons.org/licenses/by-nc-sa/4.0/ CC-BY-NC-SA 4.0
 */

/**
 * CONSTANTS_CONFIG_DEFAULT
 *
 * Declare the default values of global config options.
 *
 * @package wikindx\core\startup
 */

// Debugging
/**
 * Default values of config.php file
 * We keep here to check them at load time
 * NB: PHP 7 only can define a constant array
 */
define('WIKINDX_DEBUG_ERRORS_DEFAULT', FALSE);
define('WIKINDX_DEBUG_EMAIL_DEFAULT', FALSE);
define('WIKINDX_DEBUG_SQL_DEFAULT', FALSE);
define('WIKINDX_DEBUG_SQLERROROUTPUT_DEFAULT', 'printSql');
define('WIKINDX_BYPASS_SMARTYCOMPILE_DEFAULT', FALSE);


// Divers
define('WIKINDX_TITLE_DEFAULT', 'WIKINDX');
define('WIKINDX_CONTACT_EMAIL_DEFAULT', '');
define('WIKINDX_DESCRIPTION_DEFAULT', 'My Wikindx');
define('WIKINDX_FILE_DELETESECONDS_DEFAULT', 3600);
define('WIKINDX_PAGING_DEFAULT', 20);
define('WIKINDX_PAGING_MAXLINKS_DEFAULT', 11);
define('WIKINDX_STRINGLIMIT_DEFAULT', 40);


// Localisation
/** Default language */
define('WIKINDX_LANGUAGE_DEFAULT', 'en_GB');

/** Default time zone (GMT) */
define('WIKINDX_TIMEZONE_DEFAULT', 'UTC');


// Divers
define('WIKINDX_BASE_URL_DEFAULT', FALSE);
define('WIKINDX_TRUNK_VERSION_DEFAULT', FALSE);
define('WIKINDX_STYLE_DEFAULT', 'apa');
define('WIKINDX_TEMPLATE_DEFAULT', 'default');
define('WIKINDX_MULTIUSER_DEFAULT', FALSE);
define('WIKINDX_USERREGISTRATION_DEFAULT', FALSE);
define('WIKINDX_USERREGISTRATIONMODERATE_DEFAULT', FALSE);
define('WIKINDX_NOTIFY_DEFAULT', FALSE);
define('WIKINDX_IMG_WIDTHLIMIT_DEFAULT', 400);
define('WIKINDX_IMG_HEIGHTLIMIT_DEFAULT', 400);
define('WIKINDX_FILE_ATTACH_DEFAULT', FALSE);
define('WIKINDX_FILE_VIEWLOGGEDONONLY_DEFAULT', FALSE);
define('WIKINDX_MAXPASTE_DEFAULT', 10);
define('WIKINDX_LASTCHANGES_DEFAULT', 10);
define('WIKINDX_LASTCHANGESTYPE_DEFAULT', 'number');
define('WIKINDX_LASTCHANGESDAYLIMIT_DEFAULT', 10);
define('WIKINDX_PAGINGTAGCLOUD_DEFAULT', 100);
define('WIKINDX_IMPORTBIB_DEFAULT', FALSE);
define('WIKINDX_EMAIL_NEWS_DEFAULT', FALSE);
define('WIKINDX_EMAIL_NEWREGISTRATIONS_DEFAULT', '');
define('WIKINDX_QUARANTINE_DEFAULT', FALSE);
define('WIKINDX_LISTLINK_DEFAULT', FALSE);
define('WIKINDX_EMAIL_STATISTICS_DEFAULT', FALSE);
define('WIKINDX_STATISTICSCOMPILED_DEFAULT', '2018-01-01 01:01:01');
define('WIKINDX_METADATA_ALLOW_DEFAULT', TRUE);
define('WIKINDX_METADATA_USERONLY_DEFAULT', FALSE);
define('WIKINDX_NOSORT_DEFAULT', base64_encode(serialize(['an', 'a', 'the', 'der', 'die', 'das', 'ein', 'eine', 'einer', 'eines', 'le', 'la', 'las', 'il', 'les', 'une', 'un', 'una', 'uno', 'lo', 'los', 'i', 'gli', 'de', 'het', 'um', 'uma', 'o', 'os', 'as', 'den', 'det', 'en', 'et', ])));
define('WIKINDX_SEARCHFILTER_DEFAULT', base64_encode(serialize(['an', 'a', 'the', 'and', 'to'])));
define('WIKINDX_DEACTIVATE_RESOURCE_TYPES_DEFAULT', base64_encode(serialize([])));
define('WIKINDX_DENY_READONLY_DEFAULT', FALSE);
define('WIKINDX_READONLYACCESS_DEFAULT', TRUE);
define('WIKINDX_ORIGINATOR_EDITONLY_DEFAULT', FALSE);
define('WIKINDX_GLOBAL_EDIT_DEFAULT', FALSE);


// Database
define('WIKINDX_DB_HOST_DEFAULT', 'localhost');
define('WIKINDX_DB_DEFAULT', 'wikindx5');
define('WIKINDX_DB_USER_DEFAULT', 'wikindx');
define('WIKINDX_DB_PASSWORD_DEFAULT', 'wikindx');
define('WIKINDX_DB_TABLEPREFIX_DEFAULT', 'wkx_');
/** @see https://www.php.net/manual/en/mysqli.persistconns.php */
define('WIKINDX_DB_PERSISTENT_DEFAULT', TRUE);


// System
define('WIKINDX_RESTRICT_USERID_DEFAULT', 0);
define('WIKINDX_MEMORY_LIMIT_DEFAULT', '32M');
define('WIKINDX_MAX_WRITECHUNK_DEFAULT', 10000);
define('WIKINDX_MAX_EXECUTION_TIMEOUT_DEFAULT', FALSE);


// RSS feed
define('WIKINDX_RSS_ALLOW_DEFAULT', FALSE);
define('WIKINDX_RSS_LIMIT_DEFAULT', 10);
define('WIKINDX_RSS_BIBSTYLE_DEFAULT', WIKINDX_STYLE_DEFAULT);
define('WIKINDX_RSS_DISPLAY_DEFAULT', FALSE);
define('WIKINDX_RSS_TITLE_DEFAULT', 'WIKINDX');
define('WIKINDX_RSS_DESCRIPTION_DEFAULT', 'My Wikindx');


// LDAP
define('WIKINDX_LDAP_USE_DEFAULT', FALSE);
define('WIKINDX_LDAP_SERVER_DEFAULT', 'localhost');
define('WIKINDX_LDAP_DN_DEFAULT', '');
define('WIKINDX_LDAP_PORT_DEFAULT', 389);
define('WIKINDX_LDAP_PROTOCOL_VERSION_DEFAULT', 3);


// Auth
define('WIKINDX_AUTHGATE_USE_DEFAULT', FALSE);
define('WIKINDX_AUTHGATE_MESSAGE_DEFAULT', FALSE);
define('WIKINDX_PASSWORDSIZE_DEFAULT', 6);
define('WIKINDX_PASSWORDSTRENGTH_DEFAULT', 'strong');


// Mail system
define('WIKINDX_MAIL_SERVER_DEFAULT', FALSE);
define('WIKINDX_MAIL_FROM_DEFAULT', WIKINDX_TITLE_DEFAULT);
define('WIKINDX_MAIL_REPLYTO_DEFAULT', 'noreply@noreply.org');
define('WIKINDX_MAIL_RETURN_PATH_DEFAULT', FALSE);
define('WIKINDX_MAIL_BACKEND_DEFAULT', 'smtp');
define('WIKINDX_MAIL_SMPATH_DEFAULT', '/usr/sbin/sendmail');
define('WIKINDX_MAIL_SMTPSERVER_DEFAULT', 'localhost');
define('WIKINDX_MAIL_SMTPPORT_DEFAULT', '25');
define('WIKINDX_MAIL_SMTPENCRYPT_DEFAULT', '');
define('WIKINDX_MAIL_SMTPPERSIST_DEFAULT', FALSE);
define('WIKINDX_MAIL_SMTPAUTH_DEFAULT', FALSE);
define('WIKINDX_MAIL_SMTPUSERNAME_DEFAULT', '');
define('WIKINDX_MAIL_SMTPPASSWORD_DEFAULT', '');
define('WIKINDX_GS_ALLOW_DEFAULT', FALSE);
define('WIKINDX_GS_ATTACHMENT_DEFAULT', FALSE);


// CMS API
define('WIKINDX_CMS_ALLOW_DEFAULT', FALSE);
define('WIKINDX_CMS_BIBSTYLE_DEFAULT', WIKINDX_STYLE_DEFAULT);
define('WIKINDX_CMS_SQL_DEFAULT', FALSE);
define('WIKINDX_CMS_DB_USER_DEFAULT', '');
define('WIKINDX_CMS_DB_PASSWORD_DEFAULT', '');


// Divers
define('WIKINDX_TAG_LOW_COLOUR_DEFAULT', 'a0a0a0');
define('WIKINDX_TAG_HIGH_COLOUR_DEFAULT', 'ff0000');
define('WIKINDX_TAG_LOW_FACTOR_DEFAULT', 100);
define('WIKINDX_TAG_HIGH_FACTOR_DEFAULT', 200);
define('WIKINDX_IMAGES_ALLOW_DEFAULT', FALSE);
define('WIKINDX_IMAGES_MAXSIZE_DEFAULT', 5);
define('WIKINDX_SITEMAP_ALLOW_DEFAULT', FALSE);


// Statistics
define('WIKINDX_DISPLAY_STATISTICS_DEFAULT', FALSE);
define('WIKINDX_DISPLAY_USER_STATISTICS_DEFAULT', FALSE);
